// Generated by CoffeeScript 1.10.0
(function() {
  var locationsSchema, mongoose;

  mongoose = require('mongoose');

  locationsSchema = new mongoose.Schema({
    name: String,
    address: String,
    rating: {
      type: Number,
      "default": 0,
      min: 0,
      max: 5
    },
    facilities: [String],
    coords: {
      type: [Number],
      index: '2dsphere'
    }
  });

}).call(this);
