// Generated by CoffeeScript 1.10.0
(function() {
  module.exports.homelist = function(req, res) {
    return res.render('locations-list', {
      title: 'Home'
    });
  };

  module.exports.locationInfo = function(req, res) {
    return res.render('location-info', {
      title: 'Location info'
    });
  };

  module.exports.addReview = function(req, res) {
    return res.render('location-review-form', {
      title: 'Add review'
    });
  };

}).call(this);
